live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Underline"

[selection]
save_to_clipboard = false

[window]
decorations = "full"
dynamic_title = true
# history = 10000
# multiplier = 3
opacity = 0.75

[window.padding]
x = 32
y = 32
