[colors.primary]
background = "0x0b0f17"
foreground = "0x919191"

[colors.normal]
black = "0x303030"
red = "0xc10023"
green = "0xa83334"
yellow = "0xb51d2c"
blue = "0x8c4b46"
magenta = "0x7d534f"
cyan = "0x9a413d"
white = "0xc6c6c6"

[colors.bright]
black = "0x5e5e5e"
red = "0xff8781"
green = "0xffa095"
yellow = "0xff948b"
blue = "0xfeb2aa"
magenta = "0xebbbb5"
cyan = "0xffaaa0"
white = "0xffffff"
