colors:
  # Default colors
  primary:
    background: '0x101010'
    foreground: '0xf8f8f6'

  # Normal colors
  normal:
    black:   '0x242424'
    red:     '0xff8989'
    green:   '0xf2ff8a'
    yellow:  '0xfefa67'
    blue:    '0xa978f6'
    magenta: '0xfd56f9'
    cyan:    '0x8afeff'
    white:   '0xfefefe'

  # Bright colors
  bright:
    black:   '0x323232'
    red:     '0xff9898'
    green:   '0xf7ff9f'
    yellow:  '0xfeff57'
    blue:    '0xaddef8'
    magenta: '0xfe78ff'
    cyan:    '0x8affff'
    white:   '0xffffff'
