#!/bin/sh

for archivos in ~/.config/bspwm/style_folder/nord/config/*; do
	cp -R "${archivos}" ~/.config/
done

cp -f "$HOME"/.config/bspwm/style_folder/nord/home/.fehbg "$HOME"

bspc wm -r
pkill -USR1 -x sxhkd
