#!/bin/sh
# Autostart file for penguinRice

# Xresources
xrdb merge ~/.Xresources &

# Wallpaper
~/.fehbg &

# Bar
~/.config/bspwm/bin/bar &

# Compositor
picom --config ~/.config/bspwm/config/picom/picom.conf &

# Network Manager Applet
nm-applet &

# Screenshot
flameshot &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Notification
killall -q dunst
dunst -config ~/.config/bspwm/config/dunst/dunstrc &

# Autolock
xss-lock -- ~/.config/bspwm/bin/blur-lock &

# Ibus daemon
ibus-daemon -drx &

