#!/bin/sh
# penguinRice

# Start sxhkd
killall -q sxhkd
sleep 0.2
sxhkd -c ~/.config/bspwm/config/sxhkdrc &

# Workspaces
# workspaces() {
# 	for monitor in "$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)"; do
# 		bspc monitor "${monitor}" -d '1' '2' '3' '4' '5' '6' '7' '8' '9'
# 	done
# }
#
# workspaces

# bspwm config
bspc config pointer_follows_monitor true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc rule -a URxvt:scratchy sticky=on state=floating rectangle=widthxheight+Xoffset+Yoffset
bspc config window_gap 3
bspc config focus_follows_pointer true
bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false


# bspc monitor eDP1 -d '1' '2' '3' '4' 
# bspc monitor HDMI1 -d '5' '6' '7' '8' '9'

	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	# INTERNAL_MONITOR="eDP1"
	# EXTERNAL_MONITOR="HDMI1"
	# if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
	# 	bspc monitor "$EXTERNAL_MONITOR" -d '5' '6' '7' '8' '9'
	# 	bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' 
	# 	bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR" 	
 #  else
	# 	bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8' '9'
	#
	#
	# fi
	#

INTERNAL_MONITOR="eDP1"
EXTERNAL_MONITOR="HDMI1"
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$EXTERNAL_MONITOR" -d '7' '8' '9' '10' '11' '12'
    bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6'
    bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
else
    bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12'

fi
# Screen setup
~/.screenlayout/monitor.sh

# Config files
~/.config/bspwm/config/bsp-config

# Autostart
~/.config/bspwm/autostart

# Cursor config
xsetroot -cursor_name left_ptr

export _JAVA_AWT_WM_NONREPARENTING=1
