colors:
  # Default colors
  primary:
    background: '#f3f3f3'
    foreground: '#424153'

  # Normal colors
  normal:
    black:   '#4b4646'
    red:     '#996633'
    green:   '#0abf0a'
    yellow:  '#dada00'
    blue:    '#333399'
    magenta: '#d7a0e6'
    cyan:    '#999999'
    white:   '#dddddd'

  # Bright colors
  bright:
    black:   '#4b4646'
    red:     '#996633'
    green:   '#0abf0a'
    yellow:  '#dada00'
    blue:    '#333399'
    magenta: '#d7a0e6'
    cyan:    '#999999'
    white:   '#dddddd'

